version: 2
jobs:
  build:
    docker:
      - image: meteor/circleci:latest
    steps:
      - checkout
      - run: 'curl https://install.meteor.com | /bin/sh'
      - run: 'meteor npm install'
      - run: 'npm test --verbose'
      - run: 'meteor test --once --driver-package meteortesting:mocha'
